### PR TITLE
Add space rules (and ignore tags)

### PR DESCRIPTION
**Pull request by perrin4869**
Hi, made a few simple new rules that I think should be there by default, for your consideration!

### CODE REVIEW

**Comment by perrin4869** [comment]
I guess that the only thing missing would be some tests for these new rules

**Comment by dan-silva** [comment]
Maybe the `(\%#$` `{\%#$` and `\[\%#$` mappings should be removed, as it conflicts with the following sequence:

```
Before        Input         After~
------------------------------------
foo |         {             foo {}
------------------------------------
foo {|}       <cr>          foo {
                              |
                            }
------------------------------------
foo {|        <space>       foo { }
  
}                           }
```

There are good chances that someone will try to put a `// comment` on there, or a `|foo|` in Ruby files.

**Comment by perrin4869** [comment]
yup, you're right, fixed!
also, the tests seem to fail, but I've no clue why...

**Comment by cohama** [comment]
I don't think this rule should be by default.
Because I can't believe many people want it.

Does anyone else have any opinion?

**Comment by dan-silva** [comment]
Well, [delimitMate](https://github.com/Raimondi/delimitMate/blob/master/doc/delimitMate.txt#L208) and [auto-pairs](https://github.com/jiangmiao/auto-pairs/blob/master/README.md) provide this functionality, and as a JavaScript delevoper it is really useful when writing something like this:
```
var foo = { bar: 42 };
```
... it is very common to write it all around the code.

Maybe for consistency reasons or to allow an easier migration from these plugins it would be nice to have these rules built-in, or at least to have an example on the README showing how to do it easily.

**Comment by perrin4869** [comment]
I also think it should be on by default, because I can't think of a situation where I would not want the extra space added, but I'm fine either way.

**Comment by cohama** [comment]
> Well, delimitMate and auto-pairs provide this functionality

OK, I see.
I will merge this pull request if you fix followings.
- Remove `{<Space>` rules as @dan-silva said.
- Don't remove `{<CR>` rules, which break the current default rules. (and also some tests)
- Define `<BS>` rules like delimitMate and auto-pairs e.g. current is `( | )` and input `<BS>` then `(|)`.
- Don't modify `.gitignore`
- Add tests if you can (`vim-themis` is used for test but if you don't know, I will do it)

**Comment by perrin4869** [comment]
Oh, just saw your messages.

1) Done :)
2) Damn don't know why I removed those, gonna return them
3) Will do!
4) Hm... Why not ignore the tags though?
5) Good opportunity to pick up vim-themis!

**Comment by perrin4869** [comment]
ok, I'm basically done with all the points except 4... I just don't get why not add tags to gitignore since it's generated automatically in all environments

**Comment by cohama** [comment]
uh... I am using [neobundle](https://github.com/Shougoo/neobundle) as plugin manager and `doc/tags` directory has not been generated.
O.K. I will merge your `.gitignore` change.

Finally you should squash your changes into 2 commits. (using `git rebase -i` and `git push -f`)
One is 'Add space rules' and another is 'Ignore doc/tags'.

**Comment by cohama** [comment]
oops. test failed.
But it seems your commits do not affect to this. I will try to find the reason.

**Comment by perrin4869** [comment]
Done :)

**Comment by cohama** [comment]
Thank you very much!

**Comment by perrin4869** [comment]
Awesome! Thank you too! By the way, I raised an issue regarding mapping a few days ago, I'd appreciate it if you could take a look at it!

**Pull request merged**
